FROM nginx:latest

COPY nginx.conf /etc/nginx/conf.d/nginx.conf

RUN rm -rf /etc/nginx/conf.d/default.conf

RUN mkdir -p /usr/share/nginx/html/static \
 && mkdir -p /usr/share/nginx/html/media \
 && mkdir -p /usr/share/nginx/ssl

COPY static /usr/share/nginx/html/static

CMD ["nginx", "-g", "daemon off;"]
